name = "Simple SMP Pack"
author = "DovisPas"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a75f4466bf93ccca0054397dbf036ccee91b17c743ffd39af4e56189cd7fa680"

[versions]
fabric = "0.18.4"
minecraft = "1.21.11"

[options]
acceptable-game-versions = []
