name = "Simple SMP Pack"
author = "DovisPas"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3f10abdabbd7a1e3951d2e2402f53f0cb48cf0d9b491a86ef49a4eef2d89c7f0"

[versions]
fabric = "0.18.4"
minecraft = "1.21.11"

[options]
acceptable-game-versions = []
