name = "Simple SMP Pack"
author = "DovisPas"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d5ddece211efd626ca84eea0bca752ade2437815be4c4f6293c50f0c7e1675b7"

[versions]
fabric = "0.18.4"
minecraft = "1.21.11"

[options]
acceptable-game-versions = []
